#!/usr/bin/env bash

LATEST_VERSION="4"
echo $DOCKER_TAG
if [ "$DOCKER_TAG" = "latest" ]; then
	VARNISH_VERSION=$LATEST_VERSION
else
	VARNISH_VERSION=$DOCKER_TAG
fi

if [ "$VARNISH_VERSION" = "4" ]; then
	BASE_IMAGE=jessie-slim
elif [ "$VARNISH_VERSION" = "5" ]; then
	BASE_IMAGE=stretch-slim
else
	echo "Need to specify base image"
	exit 1
fi

docker build -t ${IMAGE_NAME} \
	--build-arg=BASE_IMAGE=$BASE_IMAGE \
	--build-arg=VARNISH_VERSION=$VARNISH_VERSION \
	.
